#!/bin/env bash
# =============================================================================
# Script  : addcert.sh
# Summary : Create RACF keyring and server certificate for Bank of Z.
#           Run once per ZVDT image (called by setup-common.sh).
#
# Both Liberty servers (BAQ<APP_SHORT_NAME> z/OS Connect + FE<APP_SHORT_NAME> frontend)
# share the same RACF keyring:
#   keystoreType="JCERACFKS"
#   keystoreFile="safkeyring://<ZOS_ADMIN_USER>/<ZOS_KEYRING>"
#
# The server cert (with EKU serverAuth for Safari/browser compliance) is
# generated by gencert-eku.sh using a re-sign approach:
#   - RACDCERT GENCERT SIGNWITH(CERTAUTH) - RACF generates keypair + cert
#     (private key stays in RACF at all times)
#   - Bouncy Castle re-signs adding EKU serverAuth + SANs + CAB Forum validity
#   - RACDCERT ADD FORMAT(CERTDER) returns the re-signed cert to RACF
# =============================================================================

# =========================
# Source library scripts
# =========================
SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPTS_DIR/../config/setenv.sh"

exec > >(while IFS= read -r line; do
    line="${line%"${line##*[![:space:]]}"}"
    [[ -z "$line" ]] && continue
    printf "${CYAN}[ADD-CERTS]${NC} %s\n" "${line}" 2>/dev/null || true
done) 2>&1

finalize_results() {
    RC=$?
    if [ $RC -eq 0 ]; then
        print_success " Process completed"
    else
        print_error "Process failed"
    fi
    exit "$RC"
}

trap finalize_results EXIT

## CUSTOMIZE ##
userid=${ZOS_ADMIN_USER}
ca_label=${ZOS_CA_LABEL}
ring=${ZOS_KEYRING}
label='BoZ'

## FIXED ##
profile=$userid.$ring.LST

# Validate required environment variable
if [[ -z "$userid" ]]; then
  print_error "ZOS_ADMIN_USER is not set"
  exit 1
fi
if [[ -z "$ca_label" ]]; then
  print_error "ZOS_CA_LABEL is not set"
  exit 1
fi

# Step 1: Create the keyring and connect VSICA as the trust anchor.
run_tso "RACDCERT ID($userid) ADDRING($ring)"
run_tso "RACDCERT ID($userid) CONNECT(CERTAUTH LABEL('$ca_label') RING($ring) USAGE(CERTAUTH))"
rc=$?
# Only DIGTRING changed - CONNECT modifies ring membership, not the cert itself
run_tso "SETROPTS RACLIST(DIGTRING) REFRESH"

# Step 2: Generate the server cert with EKU serverAuth via Bouncy Castle CSR
# round-trip (gencert-eku.sh).  The private key is generated in RACF and never
# leaves the keyring. Note: gencert-eku.sh removes any existing cert with label
# '$label' from the keyring before generating a fresh one.
if test $rc -eq 0
then
  if bash "$SCRIPTS_DIR/gencert-eku.sh"; then
    print_info "EKU cert generation succeeded - connecting cert to keyring..."
    run_tso "RACDCERT ID($userid) \
      CONNECT(LABEL('$label') RING($ring) DEFAULT)"
    rc=$?
    # Only DIGTRING changed - CONNECT modifies ring membership, not the cert itself
    run_tso "SETROPTS RACLIST(DIGTRING) REFRESH"
    if test $rc -eq 0; then
      print_success "Cert '$label' connected to keyring $userid/$ring as DEFAULT"
    else
      print_error "Failed to connect cert to keyring $userid/$ring"
    fi
  else
    print_error "gencert-eku.sh failed - Liberty cannot start without a server cert"
    rc=1
  fi
fi

# Step 3: Grant Liberty access to the keyring via RDATALIB.
# RDATALIB profile and SETROPTS are managed by grant-perm-user.sh (requires
# RACF SPECIAL). These commands are best-effort here - || true prevents abort
# if the user lacks SPECIAL authority (profile already defined by admin).
if test $rc -eq 0
then
  run_tso "RDEFINE RDATALIB $profile"  || true
  run_tso "PERMIT $profile CLASS(RDATALIB) ID($userid) ACCESS(CONTROL)"  || true
  run_tso "SETROPTS RACLIST(RDATALIB) REFRESH"  || true
  print_info "RDATALIB: run grant-perm-user.sh as admin if Liberty cannot read the keyring"
fi

exit $rc